@startuml
!pragma teoz true
RequestService: JSON resolveUrl(string url)

DIDDocService: Json MarshallProto(ProtoMsg)
DIDDocService: Json MarshallDID(Did)
DIDDocService: Json MarshallContentStream(protoiface.MessageV1, ContentType)
DIDDocService: Json MarshallVerificationMethod(protoiface.MessageV1, ContentType)
DIDDocService: protoiface.MessageV1 GetDIDFragment(Did, string fragmentId)

LedgerService: StateValue QueryDIDDoc(string id)
LedgerService: StateValue QueryResource(string id)
LedgerService: StateValue QueryCollectionResources(string id)
LedgerService: RegisterLedger(string nodeUrl)

CheqdCobraCommand: serve()

RequestService <-- DIDDocService
RequestService <-- LedgerService
CheqdCobraCommand <-- RequestService
@enduml